name: Run on every PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'extras/**'
      - '**.md'
      - '**.adoc'

jobs:
  # TODO: Add unit test as well here
  tests-linux:
    name: Xattrs bindings Tests (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        run: |
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash
      - name: Format Check
        run: make fmt-check
      - name: Lint
        run: make lint
      - name: Run Spec
        run: crystal spec spec/
  tests-darwin:
    name: Xattrs bindings Tests (Darwin)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        run: |
          brew update
          brew install crystal
      - name: Run Spec
        run: crystal spec spec/
